repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-case-conflict
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: check-toml
      - id: name-tests-test
        args: ["--pytest-test-first"]
      - id: no-commit-to-branch

  - repo: https://github.com/lk16/detect-missing-init
    rev: v0.1.6
    hooks:
      - id: detect-missing-init
        args:
          ["--create", "--track", "--python-folders", "tests,tal_stats_client"]

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.10.1
    hooks:
      - id: pyupgrade
        args: ["--py311-plus"]

  # - repo: local
  #   hooks:
  #     - id: lint-check
  #       name: lint
  #       entry: make lint
  #       language: system
  #       pass_filenames: false
  #       always_run: true

  - repo: local
    hooks:
      - id: pytest-check
        name: pytest
        entry: make test
        language: system
        pass_filenames: false
        always_run: true
        stages: [push]
